ldlidar_stl_ros2_node:
  ros__parameters:
    product_name: "LD19"
    topic_name: "/scan"
    frame_id: "base_laser"
    port_name: "/dev/ttyUSB0"
    port_baudrate: 230400
    laser_scan_dir: "Counterclockwise"
    enable_angle_crop_func: false
    angle_crop_min: 0.0
    angle_crop_max: 0.0
